# -*- coding: utf-8 -*-
"""apex planet 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-AprN2-Yg-u1xhJDWcurw5K0iiW3fR1u
"""

# ============================================
# TASK 1 : Data Immersion & Wrangling
# Project: Bank Customer Churn Analysis
# Platform: Google Colab
# ============================================

# STEP 1 — Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# STEP 2 — Upload Dataset
from google.colab import files
uploaded = files.upload()

# STEP 3 — Load Dataset
df = pd.read_csv('Churn_Modelling.csv')

# STEP 4 — Display First 5 Rows
print("FIRST 5 RECORDS")
display(df.head())

# STEP 5 — Dataset Information
print("\nDATASET INFORMATION")
df.info()

# STEP 6 — Check Dataset Shape
print("\nNUMBER OF ROWS AND COLUMNS")
print(df.shape)

# STEP 7 — Check Missing Values
print("\nMISSING VALUES")
print(df.isnull().sum())

# STEP 8 — Check Duplicate Records
print("\nDUPLICATE RECORDS")
print(df.duplicated().sum())

# STEP 9 — Remove Unnecessary Columns
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

print("\nCOLUMNS AFTER REMOVING UNWANTED COLUMNS")
print(df.columns)

# STEP 10 — Statistical Summary
print("\nSTATISTICAL SUMMARY")
display(df.describe())

# STEP 11 — Convert Exited Column
df['Exited'] = df['Exited'].replace({
    0: 'Stayed',
    1: 'Left'
})

print("\nUPDATED EXITED COLUMN")
display(df[['Exited']].head())

# STEP 12 — Check Data Types
print("\nDATA TYPES")
print(df.dtypes)

# STEP 13 — Outlier Detection Using Boxplots

# Credit Score
plt.figure(figsize=(6,4))
sns.boxplot(x=df['CreditScore'])
plt.title("Boxplot of Credit Score")
plt.show()

# Balance
plt.figure(figsize=(6,4))
sns.boxplot(x=df['Balance'])
plt.title("Boxplot of Balance")
plt.show()

# Estimated Salary
plt.figure(figsize=(6,4))
sns.boxplot(x=df['EstimatedSalary'])
plt.title("Boxplot of Estimated Salary")
plt.show()

# STEP 14 — Churn Distribution
plt.figure(figsize=(6,4))
sns.countplot(x='Exited', data=df)
plt.title("Customer Churn Distribution")
plt.show()

# STEP 15 — Geography Distribution
plt.figure(figsize=(7,4))
sns.countplot(x='Geography', data=df)
plt.title("Customers by Geography")
plt.show()

# STEP 16 — Gender Distribution
plt.figure(figsize=(6,4))
sns.countplot(x='Gender', data=df)
plt.title("Gender Distribution")
plt.show()

# STEP 17 — Save Cleaned Dataset
df.to_csv('Cleaned_Bank_Churn.csv', index=False)

print("\nCLEANED DATASET SAVED SUCCESSFULLY")

# STEP 18 — Download Cleaned Dataset
files.download('Cleaned_Bank_Churn.csv')

# ============================================
# TASK 1 COMPLETED SUCCESSFULLY
# ============================================